# Generated by Django 2.1.7 on 2019-04-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebank', '0002_auto_20190423_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codebank',
            options={'ordering': ['-created']},
        ),
    ]
